### PR TITLE
Fix bad grammar in rank command

### LINKED ISSUE #592: bad grammar in rank embed
> https://femboy.beauty/U2e_i

[Original message by @.tanji](https://discord.com/channels/741040473476694159/741057568297975928/1182712183243681823)

### PR DESCRIPTION
**Pull request by yorunoken**
fixes #592, adds suffix to the top play index and fixes the bad grammar

### CODE REVIEW

File: bathbot/src/commands/osu/rank/pp.rs [hunk 1]
```diff
@@ -803,12 +803,25 @@ impl RankData {
...
+
+                let idx_suffix = match idx % 100 {
+                    11 | 12 | 13 => "th",
+                    _ => match idx % 10 {
+                        1 => "st",
+                        2 => "nd",
+                        3 => "rd",
+                        _ => "th",
+                    },
+                };
```
Comment (MaxOhn) [inline bathbot/src/commands/osu/rank/pp.rs:816]: This can be refactored into its own function so it can be re-used. It's header could look something like
```rs
fn idx_suffix(idx: usize) -> &'static str { ... }
```

File: bathbot/src/commands/osu/rank/pp.rs [hunk 2]
```diff
@@ -803,12 +803,25 @@ impl RankData {
...
+
                 format!(
                     "{prefix}, so {username} is missing **{missing}** raw pp, achievable \
-                    with a single score worth **{pp}pp** which would be the top #{idx}.",
+                    with a single score worth **{pp}pp** which would be their {idx}{suffix} top play.",
                     missing = WithComma::new(rank_holder_pp - user_pp),
                     pp = WithComma::new(required),
-                    idx = idx + 1,
+                    idx = idx,
+                    suffix = idx_suffix
```
Comment (MaxOhn) [inline bathbot/src/commands/osu/rank/pp.rs:824]: Instead of assigning variables their own name when formatting, one can just use the variable name directly so the `idx` line isn't necessary and the `suffix` line can be removed when renaming the `idx_suffix` variable to `suffix`.

**Review by MaxOhn — CHANGES_REQUESTED** [review]
The change seems fine to me, just got a few nits

**Comment by yorunoken** [comment]
should be ready now

**Comment by MaxOhn** [comment]
Thanks :)
